### ISSUE TITLE
No module named 'flow'

### ISSUE THREAD

**Issue by HappyDay-design** [Jacklinkk/TorchGRL#3]
Thank you for sharing your code

i tried to install Flow according to your instructions
cd flow
conda env create -f environment.yml
conda activate TorchGRL
python setup.py develop

But may be I had errors when installed Flow

**Comment by Jacklinkk** [comment]
Hello, the installation of the Flow library relies on different versions of python packages according to your python environment.

Perhaps the version of the python package that Flow depends on, has some complications with the python packages you already have installed.

You can check the version of python packages in "environment.yml.", and also check packages you already installed.

**Comment by HappyDay-design** [comment]
Thank you for your quick reply.

I copy flow folder to repo and I had new errors 

(TorchGRL) osboxes@osboxes:~/Desktop/TorchGRL/GRL_Simulation$ /home/osboxes/anaconda3/envs/TorchGRL/bin/python /home/osboxes/Desktop/TorchGRL/GRL_Simulation/main.py
Traceback (most recent call last):
  File "/home/osboxes/Desktop/TorchGRL/GRL_Simulation/main.py", line 143, in <module>
    debug=DEBUG)
  File "/home/osboxes/Desktop/TorchGRL/GRL_Simulation/Experiment/DQN_experiments.py", line 119, in run
    from GRLNet.Pytorch_GRL import torch_GRL  # 导入编写的pytorch下的网络
ModuleNotFoundError: No module named 'GRLNet'

i have copied GRLNet folder to experinment folder in GRL_Simulation

**Comment by HappyDay-design** [comment]
I tried to create new file with the same command and it had errors with 
" from GRLNet.Pytorch_GRL import torch_GRL"

![image](https://user-images.githubusercontent.com/82990411/173997195-8a3e15ef-11e2-4d88-af06-2e62a523cc1c.png)

**Comment by Jacklinkk** [comment]
This may have something to do with the path of “GRLNet folder“, you can try to import the absolute path of ”GRLNet“ instead of the relative path at the beginning of your python program

**Comment by JTtht** [comment]
@TrinhTuanHung2021 Has this problem been solved?
